import CoreML
import Foundation

/// Thin Core ML wrapper for the exported gesture classifier (.mlpackage). Generic
/// over the autogenerated class so the app can load the rear model once trained.
/// Input is the LandmarkPreprocessor feature window [1, timeSteps, featureDim];
/// output is class logits in the 7-class GestureLabel order.
public struct GestureModel {
    private let model: MLModel
    private let inputName: String
    private let timeSteps: Int
    private let featureDim: Int

    public init(
        contentsOf url: URL,
        inputName: String = "landmarks",
        timeSteps: Int = LandmarkPreprocessor.targetLength,
        featureDim: Int = LandmarkPreprocessor.featureDim,
        configuration: MLModelConfiguration = MLModelConfiguration()
    ) throws {
        self.model = try MLModel(contentsOf: url, configuration: configuration)
        self.inputName = inputName
        self.timeSteps = timeSteps
        self.featureDim = featureDim
    }

    public func predict(features: [Float]) throws -> GesturePrediction {
        precondition(features.count == timeSteps * featureDim, "feature window has wrong length")
        let array = try MLMultiArray(
            shape: [1, NSNumber(value: timeSteps), NSNumber(value: featureDim)],
            dataType: .float32
        )
        let pointer = array.dataPointer.bindMemory(to: Float.self, capacity: features.count)
        for i in 0..<features.count { pointer[i] = features[i] }

        let provider = try MLDictionaryFeatureProvider(dictionary: [inputName: MLFeatureValue(multiArray: array)])
        let output = try model.prediction(from: provider)
        guard let outputName = output.featureNames.first,
              let logits = output.featureValue(for: outputName)?.multiArrayValue else {
            throw NSError(domain: "GestureModel", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: "model produced no multiarray output"])
        }
        let scores = Self.softmax(logits)
        let best = scores.enumerated().max(by: { $0.element < $1.element }) ?? (offset: 0, element: 0)
        let label = GestureLabel(rawValue: best.offset) ?? .noGesture
        return GesturePrediction(label: label, confidence: Float(best.element))
    }

    private static func softmax(_ array: MLMultiArray) -> [Double] {
        let count = array.count
        var values = (0..<count).map { array[$0].doubleValue }
        let maxValue = values.max() ?? 0
        var sum = 0.0
        for i in 0..<count { values[i] = exp(values[i] - maxValue); sum += values[i] }
        if sum > 0 { for i in 0..<count { values[i] /= sum } }
        return values
    }
}
